name: sylph
description: A utility for running Flutter integration tests on pools of real devices in cloud. Works with AWS Device Farms.
version: 0.7.0+2
homepage: https://github.com/mmcc007/sylph
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  path: ^1.6.2
  args: ^1.5.1
  yaml: ^2.1.15
  resource: ^2.1.5
  sprintf: ^4.0.2
  isolate: ^2.0.2
  duration: ^2.0.8
  version: ^1.0.3
  yamlicious: ^0.1.0
  tool_base: ^1.9.5+1
  process: ^3.0.9
  collection: ^1.14.12

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.8.0+1
  tool_base_test:
    git: https://github.com/mmcc007/tool_base_test.git
#    path: ../tool_base_test
  fake_process_manager:
    git: https://github.com/mmcc007/fake_process_manager.git
#    path: ../fake_process_manager
  mockito: ^4.1.0
  file: ^5.0.7

executables:
  sylph: main