name: sylph
description: A utility for running Flutter integration tests on pools of real devices in cloud. Works with AWS Device Farms.
version: 0.1.0
homepage: https://github.com/mmcc007/sylph
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  path: ^1.6.2
  args: ^1.5.1
  yaml: ^2.1.15
  resource: ^2.1.5

dev_dependencies:
  test: ^1.0.0

executables:
  sylph: main